packages:
  - "packages/*"
  - "examples/*"
  - "apps/*"

catalog:
  typescript: 5.9.3

minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.9.17"
  - "@turbo/darwin-arm64@2.9.17"
  - "@turbo/linux-64@2.9.17"
  - "@turbo/linux-arm64@2.9.17"
  - "@turbo/windows-64@2.9.17"
  - "@turbo/windows-arm64@2.9.17"
  - turbo@2.9.17
  - "@types/node@26.0.0"
