packages:
  - "packages/*"
  - "examples/*"
  - "apps/*"

catalog:
  typescript: 5.9.3

minimumReleaseAgeExclude:
  - prettier@3.8.5
  - '@biomejs/biome@2.5.2'
  - '@biomejs/cli-darwin-arm64@2.5.2'
  - '@biomejs/cli-darwin-x64@2.5.2'
  - '@biomejs/cli-linux-arm64-musl@2.5.2'
  - '@biomejs/cli-linux-arm64@2.5.2'
  - '@biomejs/cli-linux-x64-musl@2.5.2'
  - '@biomejs/cli-linux-x64@2.5.2'
  - '@biomejs/cli-win32-arm64@2.5.2'
  - '@biomejs/cli-win32-x64@2.5.2'
  - '@types/node@26.1.0'
